In [5]:
import numpy as np

In [6]:
B = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
A = np.array(B)
A.shape

(4, 3)

In [7]:
B

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [8]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
B[2][1]

8

In [10]:
A[2,1]

8

In [11]:
A[3,2]

12

In [17]:
A[0,0],A[1,1],A[2,2]

(1, 5, 9)

In [12]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(w, '\n')
print('The shape of w is', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

The shape of w is (3, 3, 3)


In [16]:
w[0,2,2] = 30
w[1,2,1] = 50
w[2,0,0] = 70

In [17]:
w

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 30]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 50, 18]],

       [[70, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [24]:
w[0,0,0],w[0,1,1],w[0,2,2],w[1,0,2],w[1,1,1],w[1,2,0],w[2,0,0],w[2,1,1],w[2,2,2]

(1, 5, 9, 12, 14, 16, 19, 23, 27)

In [25]:
a = np.arange(20)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


In [26]:
B = a.reshape(4,5)

In [27]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
C = B.reshape(2,10)

In [29]:
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [33]:
np_Zeros = np.zeros((10,10))

np_Zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np_Ones = np.ones((4,4))
np_Ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np_full = np.full((4,4), 10)

In [36]:
np_full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [47]:
np_eye = np.eye(10,10)

In [38]:
np_eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [1]:
import numpy as np
np_linspace = np.linspace(1, 20, num = 6)



In [5]:
np_rand = np.random.random((3,3))
np_rand

array([[0.89508947, 0.82210474, 0.02585877],
       [0.24799834, 0.3057253 , 0.69859635],
       [0.7383226 , 0.43712748, 0.75419066]])

In [4]:
np_linspace

array([ 1. ,  4.8,  8.6, 12.4, 16.2, 20. ])

In [18]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
a[0:3,2:3]

array([[ 3],
       [ 7],
       [11]])

In [29]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])